"""interior and exterior added colors in root vehicle table

Revision ID: 058df8fd4038
Revises: 446afe33c866
Create Date: 2025-07-14 12:09:22.476745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '058df8fd4038'
down_revision: Union[str, None] = '446afe33c866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('intcolor', sa.String(length=55), nullable=True))
    op.add_column('vehicles', sa.Column('extcolor', sa.String(length=55), nullable=True))
    op.drop_column('vehicles', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('color', mysql.VARCHAR(length=55), nullable=True))
    op.drop_column('vehicles', 'extcolor')
    op.drop_column('vehicles', 'intcolor')
    # ### end Alembic commands ###
