"""phone added in contact table

Revision ID: 075e00c83fd1
Revises: ae652db0a188
Create Date: 2025-06-30 09:22:12.477086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075e00c83fd1'
down_revision: Union[str, None] = 'ae652db0a188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('phone', sa.String(length=55), nullable=False))
    op.create_index(op.f('ix_messages_phone'), 'messages', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_phone'), table_name='messages')
    op.drop_column('messages', 'phone')
    # ### end Alembic commands ###
