"""Initial Revision Zeeshan Motors with all the models till customers

Revision ID: 23794e23635a
Revises: 
Create Date: 2025-06-02 17:30:03.097946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23794e23635a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctionsbigstar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_name', sa.String(length=55), nullable=True),
    sa.Column('auction_location', sa.String(length=55), nullable=True),
    sa.Column('auction_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctionsbigstar_id'), 'auctionsbigstar', ['id'], unique=False)
    op.create_table('cms_about_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sectionOneTitle', sa.String(length=255), nullable=True),
    sa.Column('sectionOneDescription', sa.Text(), nullable=True),
    sa.Column('sectionTwoTitle', sa.String(length=255), nullable=True),
    sa.Column('sectionTwoDescription', sa.Text(), nullable=True),
    sa.Column('sectionTwoImage', sa.String(length=255), nullable=True),
    sa.Column('sectionThreeTitle', sa.String(length=255), nullable=True),
    sa.Column('sectionThreeH1', sa.String(length=255), nullable=True),
    sa.Column('sectionThreeD1', sa.Text(), nullable=True),
    sa.Column('sectionThreeH2', sa.String(length=255), nullable=True),
    sa.Column('sectionThreeD2', sa.Text(), nullable=True),
    sa.Column('sectionThreeH3', sa.String(length=255), nullable=True),
    sa.Column('sectionThreeD3', sa.Text(), nullable=True),
    sa.Column('sectionFourTitle', sa.String(length=255), nullable=True),
    sa.Column('sectionFourDescription', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_about_us_id'), 'cms_about_us', ['id'], unique=False)
    op.create_table('cms_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('hours', sa.Text(), nullable=True),
    sa.Column('map_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_contact_id'), 'cms_contact', ['id'], unique=False)
    op.create_table('cms_home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heroTitle', sa.String(length=255), nullable=True),
    sa.Column('mediaItems', sa.JSON(), nullable=True),
    sa.Column('brands', sa.JSON(), nullable=True),
    sa.Column('priceRanges', sa.JSON(), nullable=True),
    sa.Column('bodyTypes', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('fairTitle', sa.String(length=255), nullable=True),
    sa.Column('fairDescription', sa.Text(), nullable=True),
    sa.Column('fairImage', sa.String(length=255), nullable=True),
    sa.Column('sliderText', sa.Text(), nullable=True),
    sa.Column('dealTitle', sa.String(length=255), nullable=True),
    sa.Column('dealDescription', sa.Text(), nullable=True),
    sa.Column('dealImage', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_home_id'), 'cms_home', ['id'], unique=False)
    op.create_table('cms_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_inventory_id'), 'cms_inventory', ['id'], unique=False)
    op.create_table('cms_product_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('h1', sa.String(length=255), nullable=True),
    sa.Column('h1Description', sa.Text(), nullable=True),
    sa.Column('h2', sa.String(length=255), nullable=True),
    sa.Column('h2Description', sa.Text(), nullable=True),
    sa.Column('h3', sa.String(length=255), nullable=True),
    sa.Column('h3Description', sa.Text(), nullable=True),
    sa.Column('title2', sa.String(length=255), nullable=True),
    sa.Column('description2', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_product_detail_id'), 'cms_product_detail', ['id'], unique=False)
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipper', sa.String(length=255), nullable=True),
    sa.Column('shipping_company', sa.String(length=255), nullable=True),
    sa.Column('bl_number', sa.String(length=255), nullable=True),
    sa.Column('container_number', sa.String(length=255), nullable=True),
    sa.Column('seal_number', sa.String(length=255), nullable=True),
    sa.Column('gross_weight', sa.String(length=255), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=255), nullable=True),
    sa.Column('port_of_loading', sa.String(length=255), nullable=True),
    sa.Column('no_of_units', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('eta', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bl_number')
    )
    op.create_index(op.f('ix_containers_id'), 'containers', ['id'], unique=False)
    op.create_table('customerauction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customerauction_id'), 'customerauction', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=55), nullable=True),
    sa.Column('last_name', sa.String(length=55), nullable=True),
    sa.Column('cell_number', sa.String(length=55), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=55), nullable=True),
    sa.Column('email_address', sa.String(length=55), nullable=True),
    sa.Column('address', sa.String(length=55), nullable=True),
    sa.Column('vat', sa.String(length=15), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('sub_total', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_id'), 'invoice', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('right_read', sa.Boolean(), nullable=True),
    sa.Column('right_write', sa.Boolean(), nullable=True),
    sa.Column('right_edit', sa.Boolean(), nullable=True),
    sa.Column('right_delete', sa.Boolean(), nullable=True),
    sa.Column('right_dashboard', sa.Boolean(), nullable=True),
    sa.Column('right_container', sa.Boolean(), nullable=True),
    sa.Column('right_product', sa.Boolean(), nullable=True),
    sa.Column('right_employee_management', sa.Boolean(), nullable=True),
    sa.Column('right_reports', sa.Boolean(), nullable=True),
    sa.Column('right_invoices', sa.Boolean(), nullable=True),
    sa.Column('right_setting', sa.Boolean(), nullable=True),
    sa.Column('right_help_center', sa.Boolean(), nullable=True),
    sa.Column('right_feed_back', sa.Boolean(), nullable=True),
    sa.Column('right_status_permission', sa.Boolean(), nullable=True),
    sa.Column('right_generate', sa.Boolean(), nullable=True),
    sa.Column('right_overseas_employee', sa.Boolean(), nullable=True),
    sa.Column('right_customer_management', sa.Boolean(), nullable=True),
    sa.Column('right_customer_management_read', sa.Boolean(), nullable=True),
    sa.Column('right_customer_management_write', sa.Boolean(), nullable=True),
    sa.Column('right_customer_management_edit', sa.Boolean(), nullable=True),
    sa.Column('right_customer_management_delete', sa.Boolean(), nullable=True),
    sa.Column('right_auction_management', sa.Boolean(), nullable=True),
    sa.Column('right_auction_management_read', sa.Boolean(), nullable=True),
    sa.Column('right_auction_management_write', sa.Boolean(), nullable=True),
    sa.Column('right_auction_management_edit', sa.Boolean(), nullable=True),
    sa.Column('right_auction_management_delete', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_by'), 'roles', ['created_by'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('phonenumber', sa.String(length=15), nullable=True),
    sa.Column('original_password', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=55), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('side', sa.String(length=55), nullable=True),
    sa.Column('terms_agreement', sa.String(length=20), nullable=True),
    sa.Column('mfa_enabled', sa.String(length=20), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('emirates_id', sa.String(length=25), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phonenumber')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_table('vehiclebodytype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehbodytype', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclebodytype_id'), 'vehiclebodytype', ['id'], unique=False)
    op.create_table('vehiclecolor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehcolor', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclecolor_id'), 'vehiclecolor', ['id'], unique=False)
    op.create_table('vehicledisplacement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehdisplacement', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicledisplacement_id'), 'vehicledisplacement', ['id'], unique=False)
    op.create_table('vehicledrivetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehdrivetype', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicledrivetype_id'), 'vehicledrivetype', ['id'], unique=False)
    op.create_table('vehiclemake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehmake', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemake_id'), 'vehiclemake', ['id'], unique=False)
    op.create_table('vehiclescore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehscore', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclescore_id'), 'vehiclescore', ['id'], unique=False)
    op.create_table('vehicletransmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehtransmission', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicletransmission_id'), 'vehicletransmission', ['id'], unique=False)
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_type', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.String(length=55), nullable=True),
    sa.Column('end_time', sa.String(length=55), nullable=True),
    sa.Column('starting_bid', sa.String(length=55), nullable=True),
    sa.Column('initial_bid_amount', sa.Float(), nullable=True),
    sa.Column('winning_bid', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('auction_house_name', sa.String(length=55), nullable=True),
    sa.Column('auction_date', sa.String(length=55), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctions_id'), 'auctions', ['id'], unique=False)
    op.create_table('itemss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=55), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('chassis_number', sa.String(length=55), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('offer_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.Column('category', sa.String(length=55), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemss_customer_id'), 'itemss', ['customer_id'], unique=False)
    op.create_index(op.f('ix_itemss_id'), 'itemss', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_fk_user_id'), 'notifications', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('personaldetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('mobilenumber', sa.String(length=15), nullable=False),
    sa.Column('ID_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ID_number'),
    sa.UniqueConstraint('mobilenumber')
    )
    op.create_index(op.f('ix_personaldetails_email'), 'personaldetails', ['email'], unique=True)
    op.create_index(op.f('ix_personaldetails_firstname'), 'personaldetails', ['firstname'], unique=False)
    op.create_index(op.f('ix_personaldetails_fk_user_id'), 'personaldetails', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_personaldetails_id'), 'personaldetails', ['id'], unique=False)
    op.create_index(op.f('ix_personaldetails_lastname'), 'personaldetails', ['lastname'], unique=False)
    op.create_table('vehiclemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehmake_id', sa.Integer(), nullable=True),
    sa.Column('vehmodel', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehmake_id'], ['vehiclemake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemodel_id'), 'vehiclemodel', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_container_id', sa.Integer(), nullable=True),
    sa.Column('fk_invoice_id', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.String(length=55), nullable=True),
    sa.Column('drive_type', sa.String(length=55), nullable=True),
    sa.Column('make', sa.String(length=55), nullable=True),
    sa.Column('model', sa.String(length=55), nullable=True),
    sa.Column('year', sa.String(length=55), nullable=True),
    sa.Column('title', sa.String(length=55), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('chassis_number', sa.String(length=55), nullable=True),
    sa.Column('mileage', sa.String(length=55), nullable=True),
    sa.Column('damage_details', sa.String(length=255), nullable=True),
    sa.Column('transmission', sa.String(length=55), nullable=True),
    sa.Column('clynder', sa.String(length=55), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('color', sa.String(length=55), nullable=True),
    sa.Column('fuel', sa.String(length=55), nullable=True),
    sa.Column('engine', sa.String(length=55), nullable=True),
    sa.Column('status', sa.String(length=55), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('qrcode', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('grade', sa.String(length=55), nullable=True),
    sa.Column('score', sa.String(length=55), nullable=True),
    sa.Column('steer', sa.String(length=55), nullable=True),
    sa.Column('displacement', sa.String(length=55), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('sold_price', sa.Float(), nullable=True),
    sa.Column('recieved_amount', sa.Float(), nullable=True),
    sa.Column('balance_amount', sa.Float(), nullable=True),
    sa.Column('auction_result', sa.String(length=55), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('doors', sa.String(length=55), nullable=True),
    sa.Column('engine_name', sa.String(length=55), nullable=True),
    sa.Column('supplier', sa.String(length=55), nullable=True),
    sa.Column('is_clear', sa.Boolean(), nullable=True),
    sa.Column('report_status', sa.String(length=20), nullable=True),
    sa.Column('feature', sa.String(length=55), nullable=True),
    sa.Column('sold_by', sa.String(length=55), nullable=True),
    sa.Column('uploaded_by', sa.String(length=55), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['fk_invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_fk_container_id'), 'vehicles', ['fk_container_id'], unique=False)
    op.create_index(op.f('ix_vehicles_fk_invoice_id'), 'vehicles', ['fk_invoice_id'], unique=False)
    op.create_index(op.f('ix_vehicles_fk_user_id'), 'vehicles', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('bidwon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('bid_amount', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bidwon_fk_user_id'), 'bidwon', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_bidwon_fk_vehicle_id'), 'bidwon', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_bidwon_id'), 'bidwon', ['id'], unique=False)
    op.create_table('comfortconvenience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('power_streeing', sa.Boolean(), nullable=True),
    sa.Column('push_start_smartkey', sa.Boolean(), nullable=True),
    sa.Column('keyless_entry', sa.Boolean(), nullable=True),
    sa.Column('key_start', sa.Boolean(), nullable=True),
    sa.Column('navigation', sa.Boolean(), nullable=True),
    sa.Column('remote_controller', sa.Boolean(), nullable=True),
    sa.Column('android_led', sa.Boolean(), nullable=True),
    sa.Column('bluetooth', sa.Boolean(), nullable=True),
    sa.Column('front_door_speaker', sa.Boolean(), nullable=True),
    sa.Column('rear_door_speaker', sa.Boolean(), nullable=True),
    sa.Column('rear_deck_speaker', sa.Boolean(), nullable=True),
    sa.Column('ECO_mode', sa.Boolean(), nullable=True),
    sa.Column('heated_seats', sa.Boolean(), nullable=True),
    sa.Column('power_seats', sa.Boolean(), nullable=True),
    sa.Column('power_side_mirrors', sa.Boolean(), nullable=True),
    sa.Column('electric_rearview_mirror', sa.Boolean(), nullable=True),
    sa.Column('dashboard_speakers', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comfortconvenience_fk_vehicle_id'), 'comfortconvenience', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_comfortconvenience_id'), 'comfortconvenience', ['id'], unique=False)
    op.create_table('comfortusabilityfeatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('riding_ergonomics', sa.Boolean(), nullable=True),
    sa.Column('seat', sa.Boolean(), nullable=True),
    sa.Column('instrumentation', sa.Boolean(), nullable=True),
    sa.Column('fuel_capacity', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comfortusabilityfeatures_fk_vehicle_id'), 'comfortusabilityfeatures', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_comfortusabilityfeatures_id'), 'comfortusabilityfeatures', ['id'], unique=False)
    op.create_table('conveniencefeatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('lighting', sa.Boolean(), nullable=True),
    sa.Column('storage', sa.Boolean(), nullable=True),
    sa.Column('security', sa.Boolean(), nullable=True),
    sa.Column('adjustable_suspension', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conveniencefeatures_fk_vehicle_id'), 'conveniencefeatures', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_conveniencefeatures_id'), 'conveniencefeatures', ['id'], unique=False)
    op.create_table('customerauctionsbids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_customer_id', sa.Integer(), nullable=True),
    sa.Column('fk_auctionbigstar_id', sa.Integer(), nullable=True),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_auctionbigstar_id'], ['auctionsbigstar.id'], ),
    sa.ForeignKeyConstraint(['fk_customer_id'], ['customerauction.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customerauctionsbids_fk_auctionbigstar_id'), 'customerauctionsbids', ['fk_auctionbigstar_id'], unique=False)
    op.create_index(op.f('ix_customerauctionsbids_fk_customer_id'), 'customerauctionsbids', ['fk_customer_id'], unique=False)
    op.create_index(op.f('ix_customerauctionsbids_fk_vehicle_id'), 'customerauctionsbids', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_customerauctionsbids_id'), 'customerauctionsbids', ['id'], unique=False)
    op.create_table('dimensioncapicity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('max_length', sa.String(length=255), nullable=True),
    sa.Column('height', sa.String(length=255), nullable=True),
    sa.Column('wheel_base', sa.String(length=255), nullable=True),
    sa.Column('height_including_roof_rails', sa.String(length=255), nullable=True),
    sa.Column('luggage_capacity_seatsup', sa.String(length=255), nullable=True),
    sa.Column('luggage_capacity_seatsdown', sa.String(length=255), nullable=True),
    sa.Column('width', sa.String(length=255), nullable=True),
    sa.Column('width_including_mirrors', sa.String(length=255), nullable=True),
    sa.Column('gross_vehicle_weight', sa.String(length=255), nullable=True),
    sa.Column('max_loading_weight', sa.String(length=255), nullable=True),
    sa.Column('max_roof_load', sa.String(length=255), nullable=True),
    sa.Column('number_of_seats', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimensioncapicity_fk_vehicle_id'), 'dimensioncapicity', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_dimensioncapicity_id'), 'dimensioncapicity', ['id'], unique=False)
    op.create_table('enginetransmisison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('fuel_tank_capacity', sa.String(length=255), nullable=True),
    sa.Column('max_towing_weight_braked', sa.String(length=255), nullable=True),
    sa.Column('max_towing_weight_unbraked', sa.String(length=255), nullable=True),
    sa.Column('minimum_kerbweight', sa.String(length=255), nullable=True),
    sa.Column('turning_circle_kerb_to_kerb', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enginetransmisison_fk_vehicle_id'), 'enginetransmisison', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_enginetransmisison_id'), 'enginetransmisison', ['id'], unique=False)
    op.create_table('exterior',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('fog_lights_front', sa.Boolean(), nullable=True),
    sa.Column('alloy_rims', sa.Boolean(), nullable=True),
    sa.Column('high_deck', sa.Boolean(), nullable=True),
    sa.Column('electric_pump', sa.Boolean(), nullable=True),
    sa.Column('justlow', sa.Boolean(), nullable=True),
    sa.Column('crane_step', sa.Boolean(), nullable=True),
    sa.Column('HID_headlights', sa.Boolean(), nullable=True),
    sa.Column('rear_wiper', sa.Boolean(), nullable=True),
    sa.Column('sun_visor', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exterior_fk_vehicle_id'), 'exterior', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_exterior_id'), 'exterior', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('fk_personal_id', sa.Integer(), nullable=True),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('fk_container_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=2000), nullable=True),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['fk_personal_id'], ['personaldetails.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_fk_container_id'), 'images', ['fk_container_id'], unique=False)
    op.create_index(op.f('ix_images_fk_personal_id'), 'images', ['fk_personal_id'], unique=False)
    op.create_index(op.f('ix_images_fk_user_id'), 'images', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_images_fk_vehicle_id'), 'images', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('interior',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('air_conditioner', sa.Boolean(), nullable=True),
    sa.Column('digital_odometer', sa.Boolean(), nullable=True),
    sa.Column('heater', sa.Boolean(), nullable=True),
    sa.Column('sunroof', sa.Boolean(), nullable=True),
    sa.Column('power_windows', sa.Boolean(), nullable=True),
    sa.Column('tv_led', sa.Boolean(), nullable=True),
    sa.Column('leather_seats', sa.Boolean(), nullable=True),
    sa.Column('tachometer', sa.Boolean(), nullable=True),
    sa.Column('headlight_leveler', sa.Boolean(), nullable=True),
    sa.Column('am_fm_radio', sa.Boolean(), nullable=True),
    sa.Column('climate_control', sa.Boolean(), nullable=True),
    sa.Column('armrest_console', sa.Boolean(), nullable=True),
    sa.Column('rear_seat_armrest_centre_console', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interior_fk_vehicle_id'), 'interior', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_interior_id'), 'interior', ['id'], unique=False)
    op.create_table('performancefeatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('desmodromic_engine_technology', sa.Boolean(), nullable=True),
    sa.Column('fuel_injection', sa.Boolean(), nullable=True),
    sa.Column('lightweight_design', sa.Boolean(), nullable=True),
    sa.Column('high_performance_suspension', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performancefeatures_fk_vehicle_id'), 'performancefeatures', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_performancefeatures_id'), 'performancefeatures', ['id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('unit_purchase_price', sa.Float(), nullable=True),
    sa.Column('auction_fee', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('transportation_cost', sa.Float(), nullable=True),
    sa.Column('vanning', sa.Float(), nullable=True),
    sa.Column('drayage', sa.Float(), nullable=True),
    sa.Column('freight', sa.Float(), nullable=True),
    sa.Column('interest_charges', sa.Float(), nullable=True),
    sa.Column('handlinf_fees', sa.Float(), nullable=True),
    sa.Column('total_fob', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('do_delivery_order', sa.Float(), nullable=True),
    sa.Column('transport_expense', sa.Float(), nullable=True),
    sa.Column('dpa_charges', sa.Float(), nullable=True),
    sa.Column('service_charges', sa.Float(), nullable=True),
    sa.Column('bank_charges', sa.Float(), nullable=True),
    sa.Column('export_paper_cost', sa.Float(), nullable=True),
    sa.Column('local_cost_aed', sa.Float(), nullable=True),
    sa.Column('total_cnf', sa.Float(), nullable=True),
    sa.Column('yard_commission', sa.Float(), nullable=True),
    sa.Column('cost_till_yard', sa.Float(), nullable=True),
    sa.Column('other_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_fk_vehicle_id'), 'prices', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('fk_auction_id', sa.Integer(), nullable=True),
    sa.Column('pruchase_date', sa.String(length=55), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('purchase_location', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=55), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_fk_auction_id'), 'purchases', ['fk_auction_id'], unique=False)
    op.create_index(op.f('ix_purchases_fk_user_id'), 'purchases', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_purchases_fk_vehicle_id'), 'purchases', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_table('safety',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('abs_antilock_braking', sa.Boolean(), nullable=True),
    sa.Column('child_safety_lock', sa.Boolean(), nullable=True),
    sa.Column('driver_air_bag', sa.Boolean(), nullable=True),
    sa.Column('passanger_air_bag', sa.Boolean(), nullable=True),
    sa.Column('rear_seat_air_bag', sa.Boolean(), nullable=True),
    sa.Column('curtain_air_bag', sa.Boolean(), nullable=True),
    sa.Column('power_door_lock', sa.Boolean(), nullable=True),
    sa.Column('traction_control', sa.Boolean(), nullable=True),
    sa.Column('oil_brakes', sa.Boolean(), nullable=True),
    sa.Column('air_brakes', sa.Boolean(), nullable=True),
    sa.Column('tool_kit', sa.Boolean(), nullable=True),
    sa.Column('stepney_tyre', sa.Boolean(), nullable=True),
    sa.Column('foot_parking_brake', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_fk_vehicle_id'), 'safety', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_safety_id'), 'safety', ['id'], unique=False)
    op.create_table('safetyfeatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('high_performance_brakes', sa.Boolean(), nullable=True),
    sa.Column('high_quality_tires', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safetyfeatures_fk_vehicle_id'), 'safetyfeatures', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_safetyfeatures_id'), 'safetyfeatures', ['id'], unique=False)
    op.create_table('transactionss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itemss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactionss_customer_id'), 'transactionss', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactionss_id'), 'transactionss', ['id'], unique=False)
    op.create_index(op.f('ix_transactionss_item_id'), 'transactionss', ['item_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('video', sa.String(length=600), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_fk_vehicle_id'), 'videos', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_fk_vehicle_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_transactionss_item_id'), table_name='transactionss')
    op.drop_index(op.f('ix_transactionss_id'), table_name='transactionss')
    op.drop_index(op.f('ix_transactionss_customer_id'), table_name='transactionss')
    op.drop_table('transactionss')
    op.drop_index(op.f('ix_safetyfeatures_id'), table_name='safetyfeatures')
    op.drop_index(op.f('ix_safetyfeatures_fk_vehicle_id'), table_name='safetyfeatures')
    op.drop_table('safetyfeatures')
    op.drop_index(op.f('ix_safety_id'), table_name='safety')
    op.drop_index(op.f('ix_safety_fk_vehicle_id'), table_name='safety')
    op.drop_table('safety')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_fk_vehicle_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_fk_user_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_fk_auction_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_fk_vehicle_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_performancefeatures_id'), table_name='performancefeatures')
    op.drop_index(op.f('ix_performancefeatures_fk_vehicle_id'), table_name='performancefeatures')
    op.drop_table('performancefeatures')
    op.drop_index(op.f('ix_interior_id'), table_name='interior')
    op.drop_index(op.f('ix_interior_fk_vehicle_id'), table_name='interior')
    op.drop_table('interior')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_fk_vehicle_id'), table_name='images')
    op.drop_index(op.f('ix_images_fk_user_id'), table_name='images')
    op.drop_index(op.f('ix_images_fk_personal_id'), table_name='images')
    op.drop_index(op.f('ix_images_fk_container_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_exterior_id'), table_name='exterior')
    op.drop_index(op.f('ix_exterior_fk_vehicle_id'), table_name='exterior')
    op.drop_table('exterior')
    op.drop_index(op.f('ix_enginetransmisison_id'), table_name='enginetransmisison')
    op.drop_index(op.f('ix_enginetransmisison_fk_vehicle_id'), table_name='enginetransmisison')
    op.drop_table('enginetransmisison')
    op.drop_index(op.f('ix_dimensioncapicity_id'), table_name='dimensioncapicity')
    op.drop_index(op.f('ix_dimensioncapicity_fk_vehicle_id'), table_name='dimensioncapicity')
    op.drop_table('dimensioncapicity')
    op.drop_index(op.f('ix_customerauctionsbids_id'), table_name='customerauctionsbids')
    op.drop_index(op.f('ix_customerauctionsbids_fk_vehicle_id'), table_name='customerauctionsbids')
    op.drop_index(op.f('ix_customerauctionsbids_fk_customer_id'), table_name='customerauctionsbids')
    op.drop_index(op.f('ix_customerauctionsbids_fk_auctionbigstar_id'), table_name='customerauctionsbids')
    op.drop_table('customerauctionsbids')
    op.drop_index(op.f('ix_conveniencefeatures_id'), table_name='conveniencefeatures')
    op.drop_index(op.f('ix_conveniencefeatures_fk_vehicle_id'), table_name='conveniencefeatures')
    op.drop_table('conveniencefeatures')
    op.drop_index(op.f('ix_comfortusabilityfeatures_id'), table_name='comfortusabilityfeatures')
    op.drop_index(op.f('ix_comfortusabilityfeatures_fk_vehicle_id'), table_name='comfortusabilityfeatures')
    op.drop_table('comfortusabilityfeatures')
    op.drop_index(op.f('ix_comfortconvenience_id'), table_name='comfortconvenience')
    op.drop_index(op.f('ix_comfortconvenience_fk_vehicle_id'), table_name='comfortconvenience')
    op.drop_table('comfortconvenience')
    op.drop_index(op.f('ix_bidwon_id'), table_name='bidwon')
    op.drop_index(op.f('ix_bidwon_fk_vehicle_id'), table_name='bidwon')
    op.drop_index(op.f('ix_bidwon_fk_user_id'), table_name='bidwon')
    op.drop_table('bidwon')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fk_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fk_invoice_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fk_container_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_vehiclemodel_id'), table_name='vehiclemodel')
    op.drop_table('vehiclemodel')
    op.drop_index(op.f('ix_personaldetails_lastname'), table_name='personaldetails')
    op.drop_index(op.f('ix_personaldetails_id'), table_name='personaldetails')
    op.drop_index(op.f('ix_personaldetails_fk_user_id'), table_name='personaldetails')
    op.drop_index(op.f('ix_personaldetails_firstname'), table_name='personaldetails')
    op.drop_index(op.f('ix_personaldetails_email'), table_name='personaldetails')
    op.drop_table('personaldetails')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_fk_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_itemss_id'), table_name='itemss')
    op.drop_index(op.f('ix_itemss_customer_id'), table_name='itemss')
    op.drop_table('itemss')
    op.drop_index(op.f('ix_auctions_id'), table_name='auctions')
    op.drop_table('auctions')
    op.drop_index(op.f('ix_vehicletransmission_id'), table_name='vehicletransmission')
    op.drop_table('vehicletransmission')
    op.drop_index(op.f('ix_vehiclescore_id'), table_name='vehiclescore')
    op.drop_table('vehiclescore')
    op.drop_index(op.f('ix_vehiclemake_id'), table_name='vehiclemake')
    op.drop_table('vehiclemake')
    op.drop_index(op.f('ix_vehicledrivetype_id'), table_name='vehicledrivetype')
    op.drop_table('vehicledrivetype')
    op.drop_index(op.f('ix_vehicledisplacement_id'), table_name='vehicledisplacement')
    op.drop_table('vehicledisplacement')
    op.drop_index(op.f('ix_vehiclecolor_id'), table_name='vehiclecolor')
    op.drop_table('vehiclecolor')
    op.drop_index(op.f('ix_vehiclebodytype_id'), table_name='vehiclebodytype')
    op.drop_table('vehiclebodytype')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_by'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_invoice_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_customerauction_id'), table_name='customerauction')
    op.drop_table('customerauction')
    op.drop_index(op.f('ix_containers_id'), table_name='containers')
    op.drop_table('containers')
    op.drop_index(op.f('ix_cms_product_detail_id'), table_name='cms_product_detail')
    op.drop_table('cms_product_detail')
    op.drop_index(op.f('ix_cms_inventory_id'), table_name='cms_inventory')
    op.drop_table('cms_inventory')
    op.drop_index(op.f('ix_cms_home_id'), table_name='cms_home')
    op.drop_table('cms_home')
    op.drop_index(op.f('ix_cms_contact_id'), table_name='cms_contact')
    op.drop_table('cms_contact')
    op.drop_index(op.f('ix_cms_about_us_id'), table_name='cms_about_us')
    op.drop_table('cms_about_us')
    op.drop_index(op.f('ix_auctionsbigstar_id'), table_name='auctionsbigstar')
    op.drop_table('auctionsbigstar')
    # ### end Alembic commands ###
