"""motor variable added

Revision ID: 446afe33c866
Revises: b4633e3c7a66
Create Date: 2025-07-14 11:58:14.863416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446afe33c866'
down_revision: Union[str, None] = 'b4633e3c7a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('motor', sa.String(length=55), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'motor')
    # ### end Alembic commands ###
