"""Models added for user, notifications and images

Revision ID: 624b449254bd
Revises: ccbeb83745fb
Create Date: 2025-05-03 09:24:23.167017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624b449254bd'
down_revision: Union[str, None] = 'ccbeb83745fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipper', sa.String(length=255), nullable=True),
    sa.Column('shipping_company', sa.String(length=255), nullable=True),
    sa.Column('bl_number', sa.String(length=255), nullable=True),
    sa.Column('container_number', sa.String(length=255), nullable=True),
    sa.Column('seal_number', sa.String(length=255), nullable=True),
    sa.Column('gross_weight', sa.String(length=255), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=255), nullable=True),
    sa.Column('port_of_loading', sa.String(length=255), nullable=True),
    sa.Column('no_of_units', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('eta', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bl_number')
    )
    op.create_index(op.f('ix_containers_id'), 'containers', ['id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=55), nullable=True),
    sa.Column('last_name', sa.String(length=55), nullable=True),
    sa.Column('cell_number', sa.String(length=55), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=55), nullable=True),
    sa.Column('email_address', sa.String(length=55), nullable=True),
    sa.Column('address', sa.String(length=55), nullable=True),
    sa.Column('vat', sa.String(length=15), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('sub_total', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_id'), 'invoice', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('phonenumber', sa.String(length=15), nullable=True),
    sa.Column('original_password', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=55), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('side', sa.String(length=55), nullable=True),
    sa.Column('terms_agreement', sa.String(length=20), nullable=True),
    sa.Column('mfa_enabled', sa.String(length=20), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('emirates_id', sa.String(length=25), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phonenumber')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstname'), 'users', ['firstname'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_lastname'), 'users', ['lastname'], unique=False)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_fk_user_id'), 'notifications', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('personaldetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('mobilenumber', sa.String(length=15), nullable=False),
    sa.Column('ID_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ID_number'),
    sa.UniqueConstraint('mobilenumber')
    )
    op.create_index(op.f('ix_personaldetails_email'), 'personaldetails', ['email'], unique=True)
    op.create_index(op.f('ix_personaldetails_firstname'), 'personaldetails', ['firstname'], unique=False)
    op.create_index(op.f('ix_personaldetails_fk_user_id'), 'personaldetails', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_personaldetails_id'), 'personaldetails', ['id'], unique=False)
    op.create_index(op.f('ix_personaldetails_lastname'), 'personaldetails', ['lastname'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_container_id', sa.Integer(), nullable=True),
    sa.Column('fk_invoice_id', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.String(length=55), nullable=True),
    sa.Column('drive_type', sa.String(length=55), nullable=True),
    sa.Column('make', sa.String(length=55), nullable=True),
    sa.Column('model', sa.String(length=55), nullable=True),
    sa.Column('year', sa.String(length=55), nullable=True),
    sa.Column('title', sa.String(length=55), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('chassis_number', sa.String(length=55), nullable=True),
    sa.Column('mileage', sa.String(length=55), nullable=True),
    sa.Column('damage_details', sa.String(length=255), nullable=True),
    sa.Column('transmission', sa.String(length=55), nullable=True),
    sa.Column('clynder', sa.String(length=55), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('color', sa.String(length=55), nullable=True),
    sa.Column('fuel', sa.String(length=55), nullable=True),
    sa.Column('engine', sa.String(length=55), nullable=True),
    sa.Column('status', sa.String(length=55), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('qrcode', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('grade', sa.String(length=55), nullable=True),
    sa.Column('score', sa.String(length=55), nullable=True),
    sa.Column('steer', sa.String(length=55), nullable=True),
    sa.Column('displacement', sa.String(length=55), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('sold_price', sa.Float(), nullable=True),
    sa.Column('recieved_amount', sa.Float(), nullable=True),
    sa.Column('balance_amount', sa.Float(), nullable=True),
    sa.Column('auction_result', sa.String(length=55), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('doors', sa.String(length=55), nullable=True),
    sa.Column('engine_name', sa.String(length=55), nullable=True),
    sa.Column('supplier', sa.String(length=55), nullable=True),
    sa.Column('is_clear', sa.Boolean(), nullable=True),
    sa.Column('report_status', sa.String(length=20), nullable=True),
    sa.Column('feature', sa.String(length=55), nullable=True),
    sa.Column('sold_by', sa.String(length=55), nullable=True),
    sa.Column('uploaded_by', sa.String(length=55), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['fk_invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_fk_container_id'), 'vehicles', ['fk_container_id'], unique=False)
    op.create_index(op.f('ix_vehicles_fk_invoice_id'), 'vehicles', ['fk_invoice_id'], unique=False)
    op.create_index(op.f('ix_vehicles_fk_user_id'), 'vehicles', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_table('comfortconvenience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('power_streeing', sa.Boolean(), nullable=True),
    sa.Column('push_start_smartkey', sa.Boolean(), nullable=True),
    sa.Column('keyless_entry', sa.Boolean(), nullable=True),
    sa.Column('key_start', sa.Boolean(), nullable=True),
    sa.Column('navigation', sa.Boolean(), nullable=True),
    sa.Column('remote_controller', sa.Boolean(), nullable=True),
    sa.Column('android_led', sa.Boolean(), nullable=True),
    sa.Column('bluetooth', sa.Boolean(), nullable=True),
    sa.Column('front_door_speaker', sa.Boolean(), nullable=True),
    sa.Column('rear_door_speaker', sa.Boolean(), nullable=True),
    sa.Column('rear_deck_speaker', sa.Boolean(), nullable=True),
    sa.Column('ECO_mode', sa.Boolean(), nullable=True),
    sa.Column('heated_seats', sa.Boolean(), nullable=True),
    sa.Column('power_seats', sa.Boolean(), nullable=True),
    sa.Column('power_side_mirrors', sa.Boolean(), nullable=True),
    sa.Column('electric_rearview_mirror', sa.Boolean(), nullable=True),
    sa.Column('dashboard_speakers', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comfortconvenience_fk_vehicle_id'), 'comfortconvenience', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_comfortconvenience_id'), 'comfortconvenience', ['id'], unique=False)
    op.create_table('dimensioncapicity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('max_length', sa.String(length=255), nullable=True),
    sa.Column('height', sa.String(length=255), nullable=True),
    sa.Column('wheel_base', sa.String(length=255), nullable=True),
    sa.Column('height_including_roof_rails', sa.String(length=255), nullable=True),
    sa.Column('luggage_capacity_seatsup', sa.String(length=255), nullable=True),
    sa.Column('luggage_capacity_seatsdown', sa.String(length=255), nullable=True),
    sa.Column('width', sa.String(length=255), nullable=True),
    sa.Column('width_including_mirrors', sa.String(length=255), nullable=True),
    sa.Column('gross_vehicle_weight', sa.String(length=255), nullable=True),
    sa.Column('max_loading_weight', sa.String(length=255), nullable=True),
    sa.Column('max_roof_load', sa.String(length=255), nullable=True),
    sa.Column('number_of_seats', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimensioncapicity_fk_vehicle_id'), 'dimensioncapicity', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_dimensioncapicity_id'), 'dimensioncapicity', ['id'], unique=False)
    op.create_table('enginetransmisison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('fuel_tank_capacity', sa.String(length=255), nullable=True),
    sa.Column('max_towing_weight_braked', sa.String(length=255), nullable=True),
    sa.Column('max_towing_weight_unbraked', sa.String(length=255), nullable=True),
    sa.Column('minimum_kerbweight', sa.String(length=255), nullable=True),
    sa.Column('turning_circle_kerb_to_kerb', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enginetransmisison_fk_vehicle_id'), 'enginetransmisison', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_enginetransmisison_id'), 'enginetransmisison', ['id'], unique=False)
    op.create_table('exterior',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('fog_lights_front', sa.Boolean(), nullable=True),
    sa.Column('alloy_rims', sa.Boolean(), nullable=True),
    sa.Column('high_deck', sa.Boolean(), nullable=True),
    sa.Column('electric_pump', sa.Boolean(), nullable=True),
    sa.Column('justlow', sa.Boolean(), nullable=True),
    sa.Column('crane_step', sa.Boolean(), nullable=True),
    sa.Column('HID_headlights', sa.Boolean(), nullable=True),
    sa.Column('rear_wiper', sa.Boolean(), nullable=True),
    sa.Column('sun_visor', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exterior_fk_vehicle_id'), 'exterior', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_exterior_id'), 'exterior', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('fk_personal_id', sa.Integer(), nullable=True),
    sa.Column('fk_user_id', sa.Integer(), nullable=True),
    sa.Column('fk_container_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=2000), nullable=True),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['fk_personal_id'], ['personaldetails.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_fk_container_id'), 'images', ['fk_container_id'], unique=False)
    op.create_index(op.f('ix_images_fk_personal_id'), 'images', ['fk_personal_id'], unique=False)
    op.create_index(op.f('ix_images_fk_user_id'), 'images', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_images_fk_vehicle_id'), 'images', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('interior',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('air_conditioner', sa.Boolean(), nullable=True),
    sa.Column('digital_odometer', sa.Boolean(), nullable=True),
    sa.Column('heater', sa.Boolean(), nullable=True),
    sa.Column('sunroof', sa.Boolean(), nullable=True),
    sa.Column('power_windows', sa.Boolean(), nullable=True),
    sa.Column('tv_led', sa.Boolean(), nullable=True),
    sa.Column('leather_seats', sa.Boolean(), nullable=True),
    sa.Column('tachometer', sa.Boolean(), nullable=True),
    sa.Column('headlight_leveler', sa.Boolean(), nullable=True),
    sa.Column('am_fm_radio', sa.Boolean(), nullable=True),
    sa.Column('climate_control', sa.Boolean(), nullable=True),
    sa.Column('armrest_console', sa.Boolean(), nullable=True),
    sa.Column('rear_seat_armrest_centre_console', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interior_fk_vehicle_id'), 'interior', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_interior_id'), 'interior', ['id'], unique=False)
    op.create_table('safety',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('abs_antilock_braking', sa.Boolean(), nullable=True),
    sa.Column('child_safety_lock', sa.Boolean(), nullable=True),
    sa.Column('driver_air_bag', sa.Boolean(), nullable=True),
    sa.Column('passanger_air_bag', sa.Boolean(), nullable=True),
    sa.Column('rear_seat_air_bag', sa.Boolean(), nullable=True),
    sa.Column('curtain_air_bag', sa.Boolean(), nullable=True),
    sa.Column('power_door_lock', sa.Boolean(), nullable=True),
    sa.Column('traction_control', sa.Boolean(), nullable=True),
    sa.Column('oil_brakes', sa.Boolean(), nullable=True),
    sa.Column('air_brakes', sa.Boolean(), nullable=True),
    sa.Column('tool_kit', sa.Boolean(), nullable=True),
    sa.Column('stepney_tyre', sa.Boolean(), nullable=True),
    sa.Column('foot_parking_brake', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_fk_vehicle_id'), 'safety', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_safety_id'), 'safety', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_safety_id'), table_name='safety')
    op.drop_index(op.f('ix_safety_fk_vehicle_id'), table_name='safety')
    op.drop_table('safety')
    op.drop_index(op.f('ix_interior_id'), table_name='interior')
    op.drop_index(op.f('ix_interior_fk_vehicle_id'), table_name='interior')
    op.drop_table('interior')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_fk_vehicle_id'), table_name='images')
    op.drop_index(op.f('ix_images_fk_user_id'), table_name='images')
    op.drop_index(op.f('ix_images_fk_personal_id'), table_name='images')
    op.drop_index(op.f('ix_images_fk_container_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_exterior_id'), table_name='exterior')
    op.drop_index(op.f('ix_exterior_fk_vehicle_id'), table_name='exterior')
    op.drop_table('exterior')
    op.drop_index(op.f('ix_enginetransmisison_id'), table_name='enginetransmisison')
    op.drop_index(op.f('ix_enginetransmisison_fk_vehicle_id'), table_name='enginetransmisison')
    op.drop_table('enginetransmisison')
    op.drop_index(op.f('ix_dimensioncapicity_id'), table_name='dimensioncapicity')
    op.drop_index(op.f('ix_dimensioncapicity_fk_vehicle_id'), table_name='dimensioncapicity')
    op.drop_table('dimensioncapicity')
    op.drop_index(op.f('ix_comfortconvenience_id'), table_name='comfortconvenience')
    op.drop_index(op.f('ix_comfortconvenience_fk_vehicle_id'), table_name='comfortconvenience')
    op.drop_table('comfortconvenience')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fk_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fk_invoice_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_fk_container_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_personaldetails_lastname'), table_name='personaldetails')
    op.drop_index(op.f('ix_personaldetails_id'), table_name='personaldetails')
    op.drop_index(op.f('ix_personaldetails_fk_user_id'), table_name='personaldetails')
    op.drop_index(op.f('ix_personaldetails_firstname'), table_name='personaldetails')
    op.drop_index(op.f('ix_personaldetails_email'), table_name='personaldetails')
    op.drop_table('personaldetails')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_fk_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_lastname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firstname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_invoice_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_containers_id'), table_name='containers')
    op.drop_table('containers')
    # ### end Alembic commands ###
