"""all models for vehicles related data merged

Revision ID: 72a42c578142
Revises: a850ec57befb
Create Date: 2025-05-14 13:01:26.220719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a42c578142'
down_revision: Union[str, None] = 'a850ec57befb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiclebodytype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehbodytype', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclebodytype_id'), 'vehiclebodytype', ['id'], unique=False)
    op.create_table('vehiclecolor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehcolor', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclecolor_id'), 'vehiclecolor', ['id'], unique=False)
    op.create_table('vehicledisplacement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehdisplacement', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicledisplacement_id'), 'vehicledisplacement', ['id'], unique=False)
    op.create_table('vehicledrivetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehdrivetype', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicledrivetype_id'), 'vehicledrivetype', ['id'], unique=False)
    op.create_table('vehiclemake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehmake', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemake_id'), 'vehiclemake', ['id'], unique=False)
    op.create_table('vehiclescore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehscore', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclescore_id'), 'vehiclescore', ['id'], unique=False)
    op.create_table('vehicletransmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehtransmission', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicletransmission_id'), 'vehicletransmission', ['id'], unique=False)
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_container_id', sa.Integer(), nullable=True),
    sa.Column('fk_invoice_id', sa.Integer(), nullable=True),
    sa.Column('body_type', sa.String(length=55), nullable=True),
    sa.Column('drive_type', sa.String(length=55), nullable=True),
    sa.Column('make', sa.String(length=55), nullable=True),
    sa.Column('model', sa.String(length=55), nullable=True),
    sa.Column('year', sa.String(length=55), nullable=True),
    sa.Column('title', sa.String(length=55), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('chassis_number', sa.String(length=55), nullable=True),
    sa.Column('mileage', sa.String(length=55), nullable=True),
    sa.Column('damage_details', sa.String(length=255), nullable=True),
    sa.Column('transmission', sa.String(length=55), nullable=True),
    sa.Column('clynder', sa.String(length=55), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('color', sa.String(length=55), nullable=True),
    sa.Column('fuel', sa.String(length=55), nullable=True),
    sa.Column('engine', sa.String(length=55), nullable=True),
    sa.Column('status', sa.String(length=55), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('qrcode', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('grade', sa.String(length=55), nullable=True),
    sa.Column('score', sa.String(length=55), nullable=True),
    sa.Column('steer', sa.String(length=55), nullable=True),
    sa.Column('displacement', sa.String(length=55), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('sold_price', sa.Float(), nullable=True),
    sa.Column('recieved_amount', sa.Float(), nullable=True),
    sa.Column('balance_amount', sa.Float(), nullable=True),
    sa.Column('auction_result', sa.String(length=55), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('doors', sa.String(length=55), nullable=True),
    sa.Column('engine_name', sa.String(length=55), nullable=True),
    sa.Column('supplier', sa.String(length=55), nullable=True),
    sa.Column('is_clear', sa.Boolean(), nullable=True),
    sa.Column('report_status', sa.String(length=20), nullable=True),
    sa.Column('feature', sa.String(length=55), nullable=True),
    sa.Column('sold_by', sa.String(length=55), nullable=True),
    sa.Column('uploaded_by', sa.String(length=55), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['fk_invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trucks_fk_container_id'), 'trucks', ['fk_container_id'], unique=False)
    op.create_index(op.f('ix_trucks_fk_invoice_id'), 'trucks', ['fk_invoice_id'], unique=False)
    op.create_index(op.f('ix_trucks_fk_user_id'), 'trucks', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_trucks_id'), 'trucks', ['id'], unique=False)
    op.create_table('vehiclemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehmake_id', sa.Integer(), nullable=True),
    sa.Column('vehmodel', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehmake_id'], ['vehiclemake.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemodel_id'), 'vehiclemodel', ['id'], unique=False)
    op.create_table('comfortusabilityfeatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('riding_ergonomics', sa.Boolean(), nullable=True),
    sa.Column('seat', sa.Boolean(), nullable=True),
    sa.Column('instrumentation', sa.Boolean(), nullable=True),
    sa.Column('fuel_capacity', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comfortusabilityfeatures_fk_vehicle_id'), 'comfortusabilityfeatures', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_comfortusabilityfeatures_id'), 'comfortusabilityfeatures', ['id'], unique=False)
    op.create_table('conveniencefeatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('lighting', sa.Boolean(), nullable=True),
    sa.Column('storage', sa.Boolean(), nullable=True),
    sa.Column('security', sa.Boolean(), nullable=True),
    sa.Column('adjustable_suspension', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conveniencefeatures_fk_vehicle_id'), 'conveniencefeatures', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_conveniencefeatures_id'), 'conveniencefeatures', ['id'], unique=False)
    op.create_table('performancefeatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('desmodromic_engine_technology', sa.Boolean(), nullable=True),
    sa.Column('fuel_injection', sa.Boolean(), nullable=True),
    sa.Column('lightweight_design', sa.Boolean(), nullable=True),
    sa.Column('high_performance_suspension', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performancefeatures_fk_vehicle_id'), 'performancefeatures', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_performancefeatures_id'), 'performancefeatures', ['id'], unique=False)
    op.create_table('safetyfeatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('high_performance_brakes', sa.Boolean(), nullable=True),
    sa.Column('high_quality_tires', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safetyfeatures_fk_vehicle_id'), 'safetyfeatures', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_safetyfeatures_id'), 'safetyfeatures', ['id'], unique=False)
    op.create_table('spareparts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_container_id', sa.Integer(), nullable=True),
    sa.Column('fk_invoice_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.String(length=55), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=True),
    sa.Column('make', sa.String(length=55), nullable=True),
    sa.Column('model', sa.String(length=55), nullable=True),
    sa.Column('category', sa.String(length=55), nullable=True),
    sa.Column('status', sa.String(length=55), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('qrcode', sa.String(length=50), nullable=True),
    sa.Column('condition_report', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('sold_price', sa.Float(), nullable=True),
    sa.Column('recieved_amount', sa.Float(), nullable=True),
    sa.Column('balance_amount', sa.Float(), nullable=True),
    sa.Column('is_clear', sa.Boolean(), nullable=True),
    sa.Column('report_status', sa.String(length=20), nullable=True),
    sa.Column('feature', sa.String(length=55), nullable=True),
    sa.Column('sold_by', sa.String(length=55), nullable=True),
    sa.Column('uploaded_by', sa.String(length=55), nullable=True),
    sa.Column('supplier', sa.String(length=55), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['fk_invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spareparts_fk_container_id'), 'spareparts', ['fk_container_id'], unique=False)
    op.create_index(op.f('ix_spareparts_fk_invoice_id'), 'spareparts', ['fk_invoice_id'], unique=False)
    op.create_index(op.f('ix_spareparts_fk_user_id'), 'spareparts', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_spareparts_fk_vehicle_id'), 'spareparts', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_spareparts_id'), 'spareparts', ['id'], unique=False)
    op.create_table('bidwon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('fk_part_id', sa.Integer(), nullable=True),
    sa.Column('bid_amount', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_part_id'], ['spareparts.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bidwon_fk_part_id'), 'bidwon', ['fk_part_id'], unique=False)
    op.create_index(op.f('ix_bidwon_fk_user_id'), 'bidwon', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_bidwon_fk_vehicle_id'), 'bidwon', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_bidwon_id'), 'bidwon', ['id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('fk_part_id', sa.Integer(), nullable=True),
    sa.Column('fk_truck_id', sa.Integer(), nullable=True),
    sa.Column('unit_purchase_price', sa.Float(), nullable=True),
    sa.Column('auction_fee', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('transportation_cost', sa.Float(), nullable=True),
    sa.Column('vanning', sa.Float(), nullable=True),
    sa.Column('drayage', sa.Float(), nullable=True),
    sa.Column('freight', sa.Float(), nullable=True),
    sa.Column('interest_charges', sa.Float(), nullable=True),
    sa.Column('handlinf_fees', sa.Float(), nullable=True),
    sa.Column('total_fob', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('do_delivery_order', sa.Float(), nullable=True),
    sa.Column('transport_expense', sa.Float(), nullable=True),
    sa.Column('dpa_charges', sa.Float(), nullable=True),
    sa.Column('service_charges', sa.Float(), nullable=True),
    sa.Column('bank_charges', sa.Float(), nullable=True),
    sa.Column('export_paper_cost', sa.Float(), nullable=True),
    sa.Column('local_cost_aed', sa.Float(), nullable=True),
    sa.Column('total_cnf', sa.Float(), nullable=True),
    sa.Column('yard_commission', sa.Float(), nullable=True),
    sa.Column('cost_till_yard', sa.Float(), nullable=True),
    sa.Column('other_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_part_id'], ['spareparts.id'], ),
    sa.ForeignKeyConstraint(['fk_truck_id'], ['trucks.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_fk_part_id'), 'prices', ['fk_part_id'], unique=False)
    op.create_index(op.f('ix_prices_fk_truck_id'), 'prices', ['fk_truck_id'], unique=False)
    op.create_index(op.f('ix_prices_fk_vehicle_id'), 'prices', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('fk_part_id', sa.Integer(), nullable=True),
    sa.Column('video', sa.String(length=600), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_part_id'], ['spareparts.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_fk_part_id'), 'videos', ['fk_part_id'], unique=False)
    op.create_index(op.f('ix_videos_fk_vehicle_id'), 'videos', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_fk_vehicle_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_fk_part_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_fk_vehicle_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_fk_truck_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_fk_part_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_bidwon_id'), table_name='bidwon')
    op.drop_index(op.f('ix_bidwon_fk_vehicle_id'), table_name='bidwon')
    op.drop_index(op.f('ix_bidwon_fk_user_id'), table_name='bidwon')
    op.drop_index(op.f('ix_bidwon_fk_part_id'), table_name='bidwon')
    op.drop_table('bidwon')
    op.drop_index(op.f('ix_spareparts_id'), table_name='spareparts')
    op.drop_index(op.f('ix_spareparts_fk_vehicle_id'), table_name='spareparts')
    op.drop_index(op.f('ix_spareparts_fk_user_id'), table_name='spareparts')
    op.drop_index(op.f('ix_spareparts_fk_invoice_id'), table_name='spareparts')
    op.drop_index(op.f('ix_spareparts_fk_container_id'), table_name='spareparts')
    op.drop_table('spareparts')
    op.drop_index(op.f('ix_safetyfeatures_id'), table_name='safetyfeatures')
    op.drop_index(op.f('ix_safetyfeatures_fk_vehicle_id'), table_name='safetyfeatures')
    op.drop_table('safetyfeatures')
    op.drop_index(op.f('ix_performancefeatures_id'), table_name='performancefeatures')
    op.drop_index(op.f('ix_performancefeatures_fk_vehicle_id'), table_name='performancefeatures')
    op.drop_table('performancefeatures')
    op.drop_index(op.f('ix_conveniencefeatures_id'), table_name='conveniencefeatures')
    op.drop_index(op.f('ix_conveniencefeatures_fk_vehicle_id'), table_name='conveniencefeatures')
    op.drop_table('conveniencefeatures')
    op.drop_index(op.f('ix_comfortusabilityfeatures_id'), table_name='comfortusabilityfeatures')
    op.drop_index(op.f('ix_comfortusabilityfeatures_fk_vehicle_id'), table_name='comfortusabilityfeatures')
    op.drop_table('comfortusabilityfeatures')
    op.drop_index(op.f('ix_vehiclemodel_id'), table_name='vehiclemodel')
    op.drop_table('vehiclemodel')
    op.drop_index(op.f('ix_trucks_id'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_fk_user_id'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_fk_invoice_id'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_fk_container_id'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_vehicletransmission_id'), table_name='vehicletransmission')
    op.drop_table('vehicletransmission')
    op.drop_index(op.f('ix_vehiclescore_id'), table_name='vehiclescore')
    op.drop_table('vehiclescore')
    op.drop_index(op.f('ix_vehiclemake_id'), table_name='vehiclemake')
    op.drop_table('vehiclemake')
    op.drop_index(op.f('ix_vehicledrivetype_id'), table_name='vehicledrivetype')
    op.drop_table('vehicledrivetype')
    op.drop_index(op.f('ix_vehicledisplacement_id'), table_name='vehicledisplacement')
    op.drop_table('vehicledisplacement')
    op.drop_index(op.f('ix_vehiclecolor_id'), table_name='vehiclecolor')
    op.drop_table('vehiclecolor')
    op.drop_index(op.f('ix_vehiclebodytype_id'), table_name='vehiclebodytype')
    op.drop_table('vehiclebodytype')
    # ### end Alembic commands ###
