"""cms deal section

Revision ID: 776356efc3ba
Revises: a61d7dfddff4
Create Date: 2025-07-01 17:09:25.551538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776356efc3ba'
down_revision: Union[str, None] = 'a61d7dfddff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_home_deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fairTitle', sa.String(length=255), nullable=True),
    sa.Column('fairDescription', sa.Text(), nullable=True),
    sa.Column('fairImage', sa.String(length=255), nullable=True),
    sa.Column('sliderText', sa.Text(), nullable=True),
    sa.Column('dealTitle', sa.String(length=255), nullable=True),
    sa.Column('dealDescription', sa.Text(), nullable=True),
    sa.Column('dealImage', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_home_deal_id'), 'cms_home_deal', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_home_deal_id'), table_name='cms_home_deal')
    op.drop_table('cms_home_deal')
    # ### end Alembic commands ###
