"""cms home table changed

Revision ID: a61d7dfddff4
Revises: 075e00c83fd1
Create Date: 2025-07-01 15:51:42.184735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a61d7dfddff4'
down_revision: Union[str, None] = '075e00c83fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_home', 'mediaItems',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('cms_home', 'categories')
    op.drop_column('cms_home', 'dealDescription')
    op.drop_column('cms_home', 'fairImage')
    op.drop_column('cms_home', 'dealImage')
    op.drop_column('cms_home', 'priceRanges')
    op.drop_column('cms_home', 'bodyTypes')
    op.drop_column('cms_home', 'sliderText')
    op.drop_column('cms_home', 'fairDescription')
    op.drop_column('cms_home', 'dealTitle')
    op.drop_column('cms_home', 'brands')
    op.drop_column('cms_home', 'fairTitle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_home', sa.Column('fairTitle', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_home', sa.Column('brands', mysql.JSON(), nullable=True))
    op.add_column('cms_home', sa.Column('dealTitle', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_home', sa.Column('fairDescription', mysql.TEXT(), nullable=True))
    op.add_column('cms_home', sa.Column('sliderText', mysql.TEXT(), nullable=True))
    op.add_column('cms_home', sa.Column('bodyTypes', mysql.JSON(), nullable=True))
    op.add_column('cms_home', sa.Column('priceRanges', mysql.JSON(), nullable=True))
    op.add_column('cms_home', sa.Column('dealImage', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_home', sa.Column('fairImage', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_home', sa.Column('dealDescription', mysql.TEXT(), nullable=True))
    op.add_column('cms_home', sa.Column('categories', mysql.JSON(), nullable=True))
    op.alter_column('cms_home', 'mediaItems',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###
