"""roles model added and adding all tables again

Revision ID: a850ec57befb
Revises: 
Create Date: 2025-05-14 11:10:02.008182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a850ec57befb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('right_read', sa.Boolean(), nullable=True),
    sa.Column('right_write', sa.Boolean(), nullable=True),
    sa.Column('right_edit', sa.Boolean(), nullable=True),
    sa.Column('right_delete', sa.Boolean(), nullable=True),
    sa.Column('right_dashboard', sa.Boolean(), nullable=True),
    sa.Column('right_container', sa.Boolean(), nullable=True),
    sa.Column('right_product', sa.Boolean(), nullable=True),
    sa.Column('right_employee_management', sa.Boolean(), nullable=True),
    sa.Column('right_reports', sa.Boolean(), nullable=True),
    sa.Column('right_invoices', sa.Boolean(), nullable=True),
    sa.Column('right_setting', sa.Boolean(), nullable=True),
    sa.Column('right_help_center', sa.Boolean(), nullable=True),
    sa.Column('right_feed_back', sa.Boolean(), nullable=True),
    sa.Column('right_status_permission', sa.Boolean(), nullable=True),
    sa.Column('right_generate', sa.Boolean(), nullable=True),
    sa.Column('right_overseas_employee', sa.Boolean(), nullable=True),
    sa.Column('right_customer_management', sa.Boolean(), nullable=True),
    sa.Column('right_customer_management_read', sa.Boolean(), nullable=True),
    sa.Column('right_customer_management_write', sa.Boolean(), nullable=True),
    sa.Column('right_customer_management_edit', sa.Boolean(), nullable=True),
    sa.Column('right_customer_management_delete', sa.Boolean(), nullable=True),
    sa.Column('right_auction_management', sa.Boolean(), nullable=True),
    sa.Column('right_auction_management_read', sa.Boolean(), nullable=True),
    sa.Column('right_auction_management_write', sa.Boolean(), nullable=True),
    sa.Column('right_auction_management_edit', sa.Boolean(), nullable=True),
    sa.Column('right_auction_management_delete', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_by'), 'roles', ['created_by'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_by'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
