"""tables correction for error

Revision ID: affa745948c7
Revises: 72ea250be0e0
Create Date: 2025-10-07 15:01:40.407372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'affa745948c7'
down_revision: Union[str, None] = '72ea250be0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_auction_id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('is_automated', sa.String(length=55), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bids_fk_auction_id'), 'bids', ['fk_auction_id'], unique=False)
    op.create_index(op.f('ix_bids_fk_user_id'), 'bids', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_bids_fk_vehicle_id'), 'bids', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_bids_id'), 'bids', ['id'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('vehicle', 'sparepart', name='item_type_enum'), nullable=False),
    sa.Column('status', sa.String(length=55), nullable=True),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_fk_vehicle_id'), 'status_history', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_status_history_id'), 'status_history', ['id'], unique=False)
    op.create_table('vehicle_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user_id', sa.Integer(), nullable=False),
    sa.Column('fk_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('fk_bid_id', sa.Integer(), nullable=True),
    sa.Column('sold_date', sa.String(length=55), nullable=True),
    sa.Column('sold_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fk_bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fk_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_sales_fk_bid_id'), 'vehicle_sales', ['fk_bid_id'], unique=False)
    op.create_index(op.f('ix_vehicle_sales_fk_user_id'), 'vehicle_sales', ['fk_user_id'], unique=False)
    op.create_index(op.f('ix_vehicle_sales_fk_vehicle_id'), 'vehicle_sales', ['fk_vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_sales_id'), 'vehicle_sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_sales_id'), table_name='vehicle_sales')
    op.drop_index(op.f('ix_vehicle_sales_fk_vehicle_id'), table_name='vehicle_sales')
    op.drop_index(op.f('ix_vehicle_sales_fk_user_id'), table_name='vehicle_sales')
    op.drop_index(op.f('ix_vehicle_sales_fk_bid_id'), table_name='vehicle_sales')
    op.drop_table('vehicle_sales')
    op.drop_index(op.f('ix_status_history_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_fk_vehicle_id'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_bids_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_fk_vehicle_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_fk_user_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_fk_auction_id'), table_name='bids')
    op.drop_table('bids')
    # ### end Alembic commands ###
