"""may be container tables is not alligned properly

Revision ID: b20f2fcdafb6
Revises: 60c73e1c0b01
Create Date: 2025-05-21 12:37:21.390982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20f2fcdafb6'
down_revision: Union[str, None] = '60c73e1c0b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
