"""Add CMS tables for about-us, inventory, product-detail, contact

Revision ID: b2afdaaf545d
Revises: c892fd7bcecd
Create Date: 2025-05-04 16:43:49.434434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b2afdaaf545d'
down_revision: Union[str, None] = 'c892fd7bcecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_about_us', sa.Column('sectionOneTitle', sa.String(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionOneDescription', sa.Text(), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionTwoTitle', sa.String(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionTwoDescription', sa.Text(), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionTwoImage', sa.String(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionThreeTitle', sa.String(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionThreeH1', sa.String(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionThreeD1', sa.Text(), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionThreeH2', sa.String(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionThreeD2', sa.Text(), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionThreeH3', sa.String(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionThreeD3', sa.Text(), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionFourTitle', sa.String(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('sectionFourDescription', sa.Text(), nullable=True))
    op.drop_column('cms_about_us', 'section_three_d1')
    op.drop_column('cms_about_us', 'section_three_title')
    op.drop_column('cms_about_us', 'section_three_h1')
    op.drop_column('cms_about_us', 'section_three_d3')
    op.drop_column('cms_about_us', 'section_two_title')
    op.drop_column('cms_about_us', 'section_one_title')
    op.drop_column('cms_about_us', 'section_four_description')
    op.drop_column('cms_about_us', 'section_three_h2')
    op.drop_column('cms_about_us', 'section_two_description')
    op.drop_column('cms_about_us', 'section_three_h3')
    op.drop_column('cms_about_us', 'section_two_image')
    op.drop_column('cms_about_us', 'section_four_title')
    op.drop_column('cms_about_us', 'section_three_d2')
    op.drop_column('cms_about_us', 'section_one_description')
    op.add_column('cms_product_detail', sa.Column('h1Description', sa.Text(), nullable=True))
    op.add_column('cms_product_detail', sa.Column('h2Description', sa.Text(), nullable=True))
    op.add_column('cms_product_detail', sa.Column('h3Description', sa.Text(), nullable=True))
    op.drop_column('cms_product_detail', 'h2_description')
    op.drop_column('cms_product_detail', 'h1_description')
    op.drop_column('cms_product_detail', 'h3_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_product_detail', sa.Column('h3_description', mysql.TEXT(), nullable=True))
    op.add_column('cms_product_detail', sa.Column('h1_description', mysql.TEXT(), nullable=True))
    op.add_column('cms_product_detail', sa.Column('h2_description', mysql.TEXT(), nullable=True))
    op.drop_column('cms_product_detail', 'h3Description')
    op.drop_column('cms_product_detail', 'h2Description')
    op.drop_column('cms_product_detail', 'h1Description')
    op.add_column('cms_about_us', sa.Column('section_one_description', mysql.TEXT(), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_three_d2', mysql.TEXT(), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_four_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_two_image', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_three_h3', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_two_description', mysql.TEXT(), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_three_h2', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_four_description', mysql.TEXT(), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_one_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_two_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_three_d3', mysql.TEXT(), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_three_h1', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_three_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('cms_about_us', sa.Column('section_three_d1', mysql.TEXT(), nullable=True))
    op.drop_column('cms_about_us', 'sectionFourDescription')
    op.drop_column('cms_about_us', 'sectionFourTitle')
    op.drop_column('cms_about_us', 'sectionThreeD3')
    op.drop_column('cms_about_us', 'sectionThreeH3')
    op.drop_column('cms_about_us', 'sectionThreeD2')
    op.drop_column('cms_about_us', 'sectionThreeH2')
    op.drop_column('cms_about_us', 'sectionThreeD1')
    op.drop_column('cms_about_us', 'sectionThreeH1')
    op.drop_column('cms_about_us', 'sectionThreeTitle')
    op.drop_column('cms_about_us', 'sectionTwoImage')
    op.drop_column('cms_about_us', 'sectionTwoDescription')
    op.drop_column('cms_about_us', 'sectionTwoTitle')
    op.drop_column('cms_about_us', 'sectionOneDescription')
    op.drop_column('cms_about_us', 'sectionOneTitle')
    # ### end Alembic commands ###
