"""Interior and Exterior Colors added to models

Revision ID: b4633e3c7a66
Revises: f751620093d8
Create Date: 2025-07-14 11:25:54.800033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4633e3c7a66'
down_revision: Union[str, None] = 'f751620093d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicleexteriorcolor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehextcolor', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicleexteriorcolor_id'), 'vehicleexteriorcolor', ['id'], unique=False)
    op.create_table('vehicleinteriorcolor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehintcolor', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicleinteriorcolor_id'), 'vehicleinteriorcolor', ['id'], unique=False)
    op.drop_index('ix_vehiclecolor_id', table_name='vehiclecolor')
    op.drop_table('vehiclecolor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiclecolor',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehcolor', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_vehiclecolor_id', 'vehiclecolor', ['id'], unique=False)
    op.drop_index(op.f('ix_vehicleinteriorcolor_id'), table_name='vehicleinteriorcolor')
    op.drop_table('vehicleinteriorcolor')
    op.drop_index(op.f('ix_vehicleexteriorcolor_id'), table_name='vehicleexteriorcolor')
    op.drop_table('vehicleexteriorcolor')
    # ### end Alembic commands ###
