"""cms model

Revision ID: c74462f8de2e
Revises: 
Create Date: 2025-05-02 10:00:25.632185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74462f8de2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heroTitle', sa.String(length=255), nullable=True),
    sa.Column('mediaItems', sa.JSON(), nullable=True),
    sa.Column('brands', sa.JSON(), nullable=True),
    sa.Column('priceRanges', sa.JSON(), nullable=True),
    sa.Column('bodyTypes', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('fairTitle', sa.String(length=255), nullable=True),
    sa.Column('fairDescription', sa.Text(), nullable=True),
    sa.Column('fairImage', sa.String(length=255), nullable=True),
    sa.Column('sliderText', sa.Text(), nullable=True),
    sa.Column('dealTitle', sa.String(length=255), nullable=True),
    sa.Column('dealDescription', sa.Text(), nullable=True),
    sa.Column('deal_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_home_id'), 'cms_home', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_home_id'), table_name='cms_home')
    op.drop_table('cms_home')
    # ### end Alembic commands ###
