"""Add CMS tables for about-us, inventory, product-detail, contact

Revision ID: c892fd7bcecd
Revises: 624b449254bd
Create Date: 2025-05-04 16:14:53.106413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c892fd7bcecd'
down_revision: Union[str, None] = '624b449254bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_about_us',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_one_title', sa.String(length=255), nullable=True),
    sa.Column('section_one_description', sa.Text(), nullable=True),
    sa.Column('section_two_title', sa.String(length=255), nullable=True),
    sa.Column('section_two_description', sa.Text(), nullable=True),
    sa.Column('section_two_image', sa.String(length=255), nullable=True),
    sa.Column('section_three_title', sa.String(length=255), nullable=True),
    sa.Column('section_three_h1', sa.String(length=255), nullable=True),
    sa.Column('section_three_d1', sa.Text(), nullable=True),
    sa.Column('section_three_h2', sa.String(length=255), nullable=True),
    sa.Column('section_three_d2', sa.Text(), nullable=True),
    sa.Column('section_three_h3', sa.String(length=255), nullable=True),
    sa.Column('section_three_d3', sa.Text(), nullable=True),
    sa.Column('section_four_title', sa.String(length=255), nullable=True),
    sa.Column('section_four_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_about_us_id'), 'cms_about_us', ['id'], unique=False)
    op.create_table('cms_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('hours', sa.Text(), nullable=True),
    sa.Column('map_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_contact_id'), 'cms_contact', ['id'], unique=False)
    op.create_table('cms_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_inventory_id'), 'cms_inventory', ['id'], unique=False)
    op.create_table('cms_product_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('h1', sa.String(length=255), nullable=True),
    sa.Column('h1_description', sa.Text(), nullable=True),
    sa.Column('h2', sa.String(length=255), nullable=True),
    sa.Column('h2_description', sa.Text(), nullable=True),
    sa.Column('h3', sa.String(length=255), nullable=True),
    sa.Column('h3_description', sa.Text(), nullable=True),
    sa.Column('title2', sa.String(length=255), nullable=True),
    sa.Column('description2', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_product_detail_id'), 'cms_product_detail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_product_detail_id'), table_name='cms_product_detail')
    op.drop_table('cms_product_detail')
    op.drop_index(op.f('ix_cms_inventory_id'), table_name='cms_inventory')
    op.drop_table('cms_inventory')
    op.drop_index(op.f('ix_cms_contact_id'), table_name='cms_contact')
    op.drop_table('cms_contact')
    op.drop_index(op.f('ix_cms_about_us_id'), table_name='cms_about_us')
    op.drop_table('cms_about_us')
    # ### end Alembic commands ###
