"""image field name for deal_image changed to dealImage

Revision ID: ccbeb83745fb
Revises: c74462f8de2e
Create Date: 2025-05-02 10:17:16.195594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ccbeb83745fb'
down_revision: Union[str, None] = 'c74462f8de2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_home', sa.Column('dealImage', sa.String(length=255), nullable=True))
    op.drop_column('cms_home', 'deal_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_home', sa.Column('deal_image', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('cms_home', 'dealImage')
    # ### end Alembic commands ###
